#!/usr/bin/env bash


kubectl create -f kube_files/a_a_16.yaml
kubectl create -f kube_files/a_a_32.yaml
kubectl create -f kube_files/a_a_64.yaml
kubectl create -f kube_files/a_a_128.yaml
kubectl create -f kube_files/a_ar_16.yaml
kubectl create -f kube_files/a_ar_32.yaml
kubectl create -f kube_files/a_ar_64.yaml
kubectl create -f kube_files/a_ar_128.yaml
kubectl create -f kube_files/a_False_16.yaml
kubectl create -f kube_files/a_False_32.yaml
kubectl create -f kube_files/a_False_64.yaml
kubectl create -f kube_files/a_False_128.yaml
kubectl create -f kube_files/ar_a_16.yaml
kubectl create -f kube_files/ar_a_32.yaml
kubectl create -f kube_files/ar_a_64.yaml
kubectl create -f kube_files/ar_a_128.yaml
kubectl create -f kube_files/ar_ar_16.yaml
kubectl create -f kube_files/ar_ar_32.yaml
kubectl create -f kube_files/ar_ar_64.yaml
kubectl create -f kube_files/ar_ar_128.yaml
kubectl create -f kube_files/ar_False_16.yaml
kubectl create -f kube_files/ar_False_32.yaml
kubectl create -f kube_files/ar_False_64.yaml
kubectl create -f kube_files/ar_False_128.yaml
kubectl create -f kube_files/False_a_16.yaml
kubectl create -f kube_files/False_a_32.yaml
kubectl create -f kube_files/False_a_64.yaml
kubectl create -f kube_files/False_a_128.yaml
kubectl create -f kube_files/False_ar_16.yaml
kubectl create -f kube_files/False_ar_32.yaml
kubectl create -f kube_files/False_ar_64.yaml
kubectl create -f kube_files/False_ar_128.yaml
kubectl create -f kube_files/False_False_16.yaml
kubectl create -f kube_files/False_False_32.yaml
kubectl create -f kube_files/False_False_64.yaml
kubectl create -f kube_files/False_False_128.yaml
